dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: ""
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: True
render_mode: 'human' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
device: "cpu"

agent: "MultiCritic_Attention_MPDQN"
env_name: "Highway"
env_id: "highway-v0"
vectorize: "DummyVecEnv"
learner: "MultiCritic_Attention_MPDQN_Learner"
policy: "MultiCritic_Attention_MPDQNPolicy"
representation: "Basic_Identical"
runner: "DRL"
action_type: "ParameterizedAction"

is_use_attention: False   # 是否基于注意力机制

is_record_driving_data: True   # 将行驶过程中的数据存入csv
is_show_env_with_plt: True   # plot绘制场景
is_show_data_details: True   # 实时显示动作、车辆状态信息
is_do_collision_prediction: False   # 基于采样进行轨迹风险检测
is_check_traj_risk_PF: False    # 基于势场进行轨迹风险检测

representation_hidden_size:
conactor_hidden_size: [256, 256, 256,]
qnetwork_hidden_size: [256, 256, 256,]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 1
parallels: 1
buffer_size: 40000
batch_size: 128
conactor_learning_rate: 0.0001
qnetwork_learning_rate: 0.0001
gamma: 0.95
tau: 0.005

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 40000  # 在decay_step_greedy个step后减弱为end_greedy
start_noise: 0.2   # noise从均值为0的高斯分布中随机选取，0.2为高斯分布的标准差
end_noise: 0.001
decay_step_noise: 40000  # 在decay_step_noise个step后减弱为end_noise

training_frequency: 1
running_steps: 200
start_training: 5
max_episode_steps:

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

#test_steps: 10  # not used
test_episode: 100  #

log_dir: "./logs/MoC_mpdqn/"
model_dir: "./models/MoC_mpdqn/"
data_record_dir: "./data_record/MoC_mpdqn/"

actor_attention_net_config:
critic_attention_net_config: