dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: ""
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: True
render_mode: 'human' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
device: "cpu"

agent: "MPDQN"
env_name: "Highway"
env_id: "highway-v0"
vectorize: "DummyVecEnv"
learner: "MPDQN_Learner"
policy: "MPDQN_Policy"
representation: "Basic_Identical"
runner: "DRL"
action_type: "ParameterizedAction"

is_record_driving_data: True   # 将行驶过程中的数据存入csv
is_show_env_with_plt: True   # plot绘制场景
is_show_data_details: True   # 实时显示动作、车辆状态信息
is_do_collision_prediction: False   # 基于采样进行轨迹风险检测
is_check_traj_risk_PF: True    # 基于势场进行轨迹风险检测

representation_hidden_size:
conactor_hidden_size: [256, 256, 256,]
qnetwork_hidden_size: [256, 256, 256,]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 4
parallels: 1
buffer_size: 40000
batch_size: 256
conactor_learning_rate: 0.0001
qnetwork_learning_rate: 0.0001
gamma: 0.9
tau: 0.005

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 20000  # 在decay_step_greedy个step后减弱为end_greedy
start_noise: 0.2   # noise从均值为0的高斯分布中随机选取，0.2为高斯分布的标准差
end_noise: 0.001
decay_step_noise: 20000  # 在decay_step_noise个step后减弱为end_noise

training_frequency: 1
running_steps: 150
start_training: 2
max_episode_steps:

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

#test_steps: 10  # not used
test_episode: 200  #
use_HighD_test: False
total_highd_test_episode: 200  # 使用HighD时总的episode数目
using_only_init_HD: False   # 背景车辆的行为由IDM控制，HighD仅用于生成初始状态

log_dir: "./logs/mpdqn/"
model_dir: "./models/mpdqn/"
data_record_dir: "./data_record/mpdqn/"

# 暂时未用到
is_pure_HD: False
getting_chosen_hd_speed: False
using_IDM_EV: False