dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: ""
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: True
render_mode: 'human' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
device: "cpu"

agent: "DDPG"
env_name: "Highway"
env_id: "highway-v0"
vectorize: "DummyVecEnv"
learner: "DDPG_Learner"
policy: "DDPG_Policy"
representation: "Basic_Identical"
runner: "DRL"
action_type: "ContHybridDiscAction"

is_record_driving_data: True
is_show_env_with_plt: True
is_do_collision_prediction: False   # 基于采样进行轨迹风险检测
is_check_traj_risk_PF: True    # 基于势场进行轨迹风险检测

representation_hidden_size:  # If you choose Basic_Identical representation, then ignore this value
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 1
parallels: 1  # number of environments
buffer_size: 30000  # replay buffer size
batch_size: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.95
tau: 0.005

start_noise: 0.5
end_noise: 0.1
training_frequency: 1
running_steps: 200  # 1M
start_training: 10
max_episode_steps:

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5

log_dir: "./logs/ddpg_CHD/"
model_dir: "./models/ddpg_CHD/"
data_record_dir: "./data_record/ddpg_CHD/"
