dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: ""
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: True
render_mode: 'human' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
device: "cpu"

agent: "SACDIS"
env_name: "Highway"
env_id: "highway-v0"
vectorize: "DummyVecEnv"
learner: "SACDIS_Learner"
policy: "Discrete_SAC"
representation: "Basic_Identical"
runner: "DRL"
action_type:   # 由is_use_old_discrete_action决定

is_use_trajectory: True     # 是否基于轨迹行驶
is_use_old_discrete_action: False

is_record_driving_data: True   # 将行驶过程中的数据存入csv
is_show_env_with_plt: True   # plot绘制场景
is_show_data_details: True   # 实时显示动作、车辆状态信息
is_do_collision_prediction: False   # 基于采样进行轨迹风险检测
is_check_traj_risk_PF: False    # 基于势场进行轨迹风险检测

representation_hidden_size:
actor_hidden_size: [256, 256,]
critic_hidden_size: [256, 256,]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 1
parallels: 1  # number of environments
buffer_size: 30000
batch_size: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.95
alpha: 0.2
use_automatic_entropy_tuning: True
tau: 0.005

training_frequency: 1
running_steps: 100
start_training: 20
max_episode_steps:

use_grad_clip: False  # gradient normalization
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

#test_steps: 10
test_episode: 3

log_dir: "./logs/sac_dis/"
model_dir: "./models/sac_dis/"
data_record_dir: "./data_record/sac_dis/"
