dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: ""
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"  # The username of wandb when the logger is wandb.
render: True # Whether to render the environment when testing.
render_mode: 'human' # Choices: 'human', 'rgb_array'.
fps: 50  # The frames per second for the rendering videos in log file.
test_mode: False  # Whether to run in test mode.
device: "cpu"  # Choose an calculating device.

agent: "PPO_Clip"  # The agent name.
env_name: "Highway"  # The environment device.
env_id: "highway-v0"  # The environment id.
vectorize: "DummyVecEnv"  # The vecrized method to create n parallel environments. Choices: DummyVecEnv, or SubprocVecEnv.
learner: "PPOCLIP_Learner"
policy: "Gaussian_AC"  # choice: Gaussian_AC for continuous actions, Categorical_AC for discrete actions.
representation: "Basic_Identical"  # The representation name.
action_type: "ContHybridDiscAction"   #

is_record_driving_data: True   # 将行驶过程中的数据存入csv
is_show_env_with_plt: True   # plot绘制场景
is_show_data_details: True   # 实时显示动作、车辆状态信息
is_do_collision_prediction: False   # 基于采样进行轨迹风险检测
is_check_traj_risk_PF: True    # 基于势场进行轨迹风险检测

representation_hidden_size:  # The size of hidden layers for representation network.
actor_hidden_size: [256, 256, 256,]  # The size of hidden layers for actor network.
critic_hidden_size: [256, 256, 256,]  # The size of hidden layers for critic network.
activation: "leaky_relu"  # The activation function for each hidden layer.
activation_action: 'tanh'  # The activation function for the last layer of actor network.

seed: 1  # The random seed.
parallels: 1  # The number of environments to run in parallel.
running_steps: 150000  # The total running steps for all environments.
horizon_size: 8192  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_epochs: 32  # The number of training epochs.
n_minibatch: 16  # The number of minibatch for each training epoch. batch_size = buffer_size // n_minibatch.
learning_rate: 0.0001  # The learning rate.
max_episode_steps:

vf_coef: 0.25  # Coefficient factor for critic loss.
ent_coef: 0.0  # Coefficient factor for entropy loss.
target_kl: 0.25  # For PPO_KL learner.
kl_coef: 1.0  # For PPO_KL learner.
clip_range: 0.2  # The clip range for ratio in PPO_Clip learner.
gamma: 0.95  # Discount factor.
use_gae: True  # Use GAE trick.
gae_lambda: 0.95  # The GAE lambda.
use_advnorm: True  # Whether to use advantage normalization.

use_grad_clip: False  # Whether to clip the gradient during training.
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5  # The max norm of the gradient.
use_actions_mask: False  # Whether to use action mask values.
use_obsnorm: False  # Whether to use observation normalization.
use_rewnorm: False  # Whether to use reward normalization.
obsnorm_range: 5  # The range of observation if use observation normalization.
rewnorm_range: 5  # The range of reward if use reward normalization.

#test_steps: 10000  # The total steps for testing.
#eval_interval: 5000  # The evaluate interval when use benchmark method.
test_episode: 200  # The test episodes.
use_HighD_test: False
total_highd_test_episode: 200  # 使用HighD时总的episode数目
using_only_init_HD: False   # 背景车辆的行为由IDM控制，HighD仅用于生成初始状态

log_dir: "./logs/ppo_CHD/"  # The main directory of log files.
model_dir: "./models/ppo_CHD/"  # The main directory of model files.
data_record_dir: "./data_record/ppo_CHD/"


# 暂时未用到
is_pure_HD: False
getting_chosen_hd_speed: False
using_IDM_EV: False